import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar"
import { TimerProvider } from "@/context/TimerContext";
import { TonConnectUIProvider } from '@tonconnect/ui-react';

// const Url = "https://raw.githubusercontent.com/markokhman/func-course-chapter-5-code/master/public/manifest.json";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TimerProvider>
          <Navbar />
          {children}
        </TimerProvider>
      </body>
    </html>
  );
}
